<?php

namespace ContainerDigcFU0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0lC1dkaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0lC1dka' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0lC1dka'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'parameterBag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'uploader' => ['privates', 'App\\File\\FileUploader', 'getFileUploaderService', true],
        ], [
            'em' => '?',
            'parameterBag' => '?',
            'uploader' => 'App\\File\\FileUploader',
        ]);
    }
}
