<?php

namespace ContainerDigcFU0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9w84u_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9w_84u.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9w_84u.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'container' => ['privates', '.errored..service_locator.9w_84u..Symfony\\Component\\DependencyInjection\\ContainerBuilder', NULL, 'Cannot autowire service ".service_locator.9w_84u.": it references class "Symfony\\Component\\DependencyInjection\\ContainerBuilder" but no such service exists.'],
        ], [
            'container' => 'Symfony\\Component\\DependencyInjection\\ContainerBuilder',
        ]);
    }
}
