<?php

namespace ContainerDigcFU0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S8bq9vlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S8bq9vl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S8bq9vl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'builder' => ['privates', '.errored..service_locator.S8bq9vl.Symfony\\Component\\DependencyInjection\\ContainerBuilder', NULL, 'Cannot autowire service ".service_locator.S8bq9vl": it references class "Symfony\\Component\\DependencyInjection\\ContainerBuilder" but no such service exists.'],
            'container' => ['privates', '.errored..service_locator.S8bq9vl.Symfony\\Component\\DependencyInjection\\Loader\\Configurator\\ContainerConfigurator', NULL, 'Cannot autowire service ".service_locator.S8bq9vl": it references class "Symfony\\Component\\DependencyInjection\\Loader\\Configurator\\ContainerConfigurator" but no such service exists.'],
            'loader' => ['privates', '.errored..service_locator.S8bq9vl.Symfony\\Component\\Config\\Loader\\LoaderInterface', NULL, 'Cannot autowire service ".service_locator.S8bq9vl": it needs an instance of "Symfony\\Component\\Config\\Loader\\LoaderInterface" but this type has been excluded from autowiring.'],
        ], [
            'builder' => 'Symfony\\Component\\DependencyInjection\\ContainerBuilder',
            'container' => 'Symfony\\Component\\DependencyInjection\\Loader\\Configurator\\ContainerConfigurator',
            'loader' => 'Symfony\\Component\\Config\\Loader\\LoaderInterface',
        ]);
    }
}
