<?php

namespace ContainerDigcFU0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContainerBuilder2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S8bq9vl.Symfony\Component\DependencyInjection\ContainerBuilder' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ContainerBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.S8bq9vl": it references class "Symfony\\Component\\DependencyInjection\\ContainerBuilder" but no such service exists.');
    }
}
